### PR TITLE
Mobile stuff

### PR DESCRIPTION
**Pull request by asutula**

### CODE REVIEW

**Comment by asutula** [comment]
Ok, this mostly just copies and updates the build config from go-textile to build and release and publish on GH, Cocoapods and Maven. G2G.

**Comment by asutula** [comment]
Oh it also exposes a simple `Start()` and `Stop()` api in the generated mobile libs.

**Comment by asutula** [comment]
After this is merged, I'll do a RC release to verify everything is working properly.

**Review by andrewxhill — APPROVED** [review]

**Comment by Gozala** [comment]
Is https://github.com/textileio/ios-textile/issues/44 on the roadmap ? Not sure if any of the new stuff addresses it or not.

**Comment by Gozala** [comment]
Is any of that going to address https://github.com/textileio/ios-textile/issues/44 ? 

> Ok, this mostly just copies and updates the build config from go-textile to build and release and publish on GH, Cocoapods and Maven. G2G.

Now that there is [native swift package manager](https://swift.org/package-manager/) does that changes things at all ?

**Comment by asutula** [comment]
I think that app extension compatibility was limited because of the iOS textile sdks use of `UIApplication` for lifecycle management. That could have and can still be untangled by architecting the code differently (I think I actually have a branch where I started that work, but have been sidetracked). This ipfs-lite library currently doesn't contain any `UIApplication` code, but if we find it's necessary to add lifecycle management, we'll want to do it in a way where it can be decoupled from the core functionality. Need to do some testing and research about if it will be necessary to do lifecycle management with ipfs-lite.

**Pull request merged**
